Feature/button icon
union-group/MOBILE-UIAcademy pull request #29
Opened 2022-03-04 20:00 UTC by rquartaroli

2022-03-06 22:58 UTC, d3vlopes requested changes

2022-03-06 22:58 UTC, d3vlopes commented on src/components/ButtonIcon/index.tsx
> +  size = 'small',
Coloca o `medium` como valor padrão.

2022-03-06 22:58 UTC, d3vlopes commented on src/components/ButtonIcon/index.tsx
> +  fillColor,
Coloca o `green` como valor padrão.

2022-03-07 12:40 UTC, rquartaroli commented on src/components/ButtonIcon/index.tsx
> +        {title && (
Do jeito que esta, já esta funcionando assim man, desse jeito que coloquei, significa que se existir title(que será text), enfim, se ele existir mostra, caso não exista, não vai mostrar, já esta funcionando como boolean...

2022-03-07 13:05 UTC, rquartaroli commented on src/components/ButtonIcon/ButtonIcon.test.tsx
> +      backgroundColor: theme.colors.secondary,
Feito

2022-03-07 14:07 UTC, d3vlopes commented on src/components/ButtonIcon/index.tsx
> +        {title && (
Sim, ele funciona mais é uma boa prática fazer dessa forma que eu falei.

2022-03-10 22:18 UTC, d3vlopes requested changes

2022-03-10 22:18 UTC, d3vlopes commented on src/components/ButtonIcon/index.tsx
> +  iconName: keyof typeof AntDesign.glyphMap
Mudar para utilizar SVG

2022-03-11 11:40 UTC, d3vlopes requested changes

2022-03-11 11:40 UTC, d3vlopes commented on src/components/ButtonIcon/index.tsx
> +}
Criar uma função chamada `selectSizeIcon` em `utils` e adiciona essa função lá.

2022-03-11 11:40 UTC, d3vlopes commented on src/components/ButtonIcon/index.tsx
> +      return RFValue(8)
Vamos mudar para 12, ficou muito pequeno 8

2022-03-11 11:40 UTC, d3vlopes commented on src/components/ButtonIcon/index.tsx
> +      return RFValue(14)
Aqui é 16

2022-03-11 11:40 UTC, d3vlopes commented on src/components/ButtonIcon/styles.ts
> +    background-color: white;
Utiliza o `white` do `theme`.

2022-03-12 14:36 UTC, d3vlopes approved these changes

2022-03-12 14:38 UTC, d3vlopes approved these changes

2022-03-12 14:38 UTC, merged